select * from TBLNOTLAR

update TBLNOTLAR set ORTLAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE NOTID =20

UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTLAMA<50


-- DERSLER TABLOSUNDA ÝSMÝ MATEMATÝK OLAN DERSE AÝT SINAV NOT BÝLGÝSÝ--
-- SUB QUERY

-- NOTLAR TABLOSUNDAKÝ ALGORÝTMA DERSÝNE AÝT EN YÜKSEK SINAV 1 Ý GETÝREN SORGU


SELECT * FROM TBLNOTLAR WHERE DERS=(SELECT DERSID FROM TBLDERSLER WHERE DERSAD='MATEMATÝK')

SELECT MAX(SINAV1)AS 'Algoritma En Yüksek Not' FROM TBLNOTLAR WHERE DERS=(SELECT DERSID FROM TBLDERSLER WHERE DERSAD='Algoritma')
