--select 20+4 as 'toplam',20-4 as 'fark',20*4 as 'çarpim',20/4 as 'bölüm'

SELECT * FROM TBLNOTLAR WHERE DERS=1

-- SORU SINAV2 NOTU 45 ÝN ALTINDA OLAN ÖÐRENCÝLERE 10 PUAN EKLEYELÝM 

UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE DERS=1



--SORU SINAV2 NOTUNA 10 PUAN EKLEDÝÐÝMÝZ NOTLARIN 100 DEN FAZLAYSA 100 EÞÝTLENMESÝ SORGUSU

UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100



-- DERSÝ 1 OLANLARI GETÝRME

SELECT * FROM TBLNOTLAR WHERE DERS=1


-- UPDATE YAPARAK DERS 1 ÝN ORTALMASINI GETÝRDÝK VE KALDI GEÇTÝ DURUMLARINI AYARLADIK SORGUYLA

UPDATE TBLNOTLAR SET ORTLAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1

UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTLAMA>=50

UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTLAMA<50


-- 1 NUMARALARI DERSLERÝN TOPLAMININ ORTALAMASI SORGUSU

SELECT AVG(ORTLAMA) FROM TBLNOTLAR WHERE DERS=1





