
SELECT * FROM TBLURUNLER

update TBLURUNLER set URUNAD='KETTLE' WHERE URUNAD='SU ISITICISI'

update TBLURUNLER set URUNAD='SU ISITICISI' WHERE URUNAD='KETTLE'



SELECT KATEGORIAD,COUNT (*) AS 'TOPLAM URUN' FROM TBLURUNLER INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID GROUP BY KATEGORIAD ORDER BY COUNT(*)




-- KATEGORÝ ADI BÝLGÝSAYAR OLAN ÜRÜNLERÝN SATIÞ FÝYATINA 500 LÝRA ZAM YAPALIM

UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR')



-- TV KATEGORÝSÝNDEKÝ  ÜRÜNLERE YÜZDE 10 ÝNDÝRÝM YAPAN SORUGUYU YAZIN

UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT-(URUNSATISFIYAT*10)/100 WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='TV')




SELECT COUNT(*) AS 'KAÇ FARKLI ÜRÜN',SUM (URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER



SELECT * FROM TBLURUNLER




-- Soru stoðumdaki bütün ürünleri satarsam ne kadar para kazanýrým



-- stoðumdaki simens buzdolaplarýný hepsini satarsam kaç para kazanýrým sorugusu



select urunýd,urunad,urunmarka,kategorIad,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,
(URUNSATISFIYAT-URUNALISFIYAT) as 'kar',(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK as 'toplam kar'
from TBLURUNLER inner join TBLKATEGORI on TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID







