

-- PROSEDUR EKLEME

create procedure DENEME
AS

SELECT * FROM TBLURUNLER WHERE URUNSTOK>10


EXEC DENEME


-- PROCEDUR SÝLME


DROP PROCEDURE DENEME


-- PROCEDUR GÜNCELLEME


ALTER procedure [dbo].[HAREKETLER]
AS
select HAREKETID,URUNAD,LEFT(MUSTERIAD,1) + ' '+ MUSTERISOYAD as 'Ad Soyad',PERSONELADSOYAD,ADET,TUTAR,TARIH from TBLHAREKET
 inner join TBLURUNLER
on TBLHAREKET.URUN=TBLURUNLER.URUNID
inner join TBLMUSTERI
on TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
inner join TBLPERSONEL
on TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

EXEC HAREKETLER



