
--BU SORGUMUZ DA 1 EKÝM ÝLE 3 EKÝM ARASINDA SATILAN ÜRÜNLERÝ SORGULATMIÞ OLDUK

select * from TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3



--BU SORGUMUZ DA 3 EKÝM ÝLE 5 EKÝM ARASINDA SATILAN ÜRÜNLERÝ SORGULATMIÞ OLDUK

select * from TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 3 AND 5



--BU SORGUMUZ DA 3 EKÝM DE SATILAN ÜRÜNLERÝ SORGULATMIÞ OLDUK

select * from TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 3 AND 3



-- BU SORGUMUZDA 3 ÝLE 5 EKÝM ARASINDA 1 NOLU MÜÞTERÝYE SATTIGIMIZ ÜRÜNLERÝ SORGULADIK

select * from TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 3 AND 5 AND MUSTERI = 1



-- BU SORGUMUZDA 1 ÝLE 5 EKÝMLERÝ ARASINDA SEHRI ANKARA OLAN MÜSTERÝYE SATTIGIMIZ ÜRÜNLERÝ SORGULADIK

SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 5 AND MUSTERI = (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ANKARA')











