



-- Adanalý Veya Ankaralý müþterilere satýlan ürünlerin toplam fiyatý


select sum(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ADANA' OR MUSTERISEHIR='ANKARA')



-- SATILAN ÜRÜNLERÝN STOÐUNU AZALTMA SORGUSU


--NOT UPDATE YAPARKEN WHERE ÞARTINI UNUTMA


UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=1) WHERE URUNID=1


UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=2) WHERE URUNID=2

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=3) WHERE URUNID=3

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=4) WHERE URUNID=4

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=5) WHERE URUNID=5

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=6) WHERE URUNID=6

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=7) WHERE URUNID=7

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=8) WHERE URUNID=8

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=9) WHERE URUNID=9

UPDATE TBLURUNLER SET URUNSTOK = URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=10) WHERE URUNID=10
