
USE DbYeni


CREATE TRIGGER ARTTIR 
ON TBLURUN -- NEYÝ ATTIR TBL ÜRÜN SAYISINI
AFTER INSERT -- NE ZAMAN ARTTIR INSERT ÝÞLEMÝ GERÇEKLEÞTÝÐÝ ZAMAN
AS UPDATE TBLSTOK SET TOPLAMURUN+=1 -- EKLEME YAPTIKTAN SONRA NE YAP GÜNCELLE EKLEME YAPILDIÐI ZAMAN

--AS UPDATE TBLSTOK SET TOPLAMURUN-=1 konuyla alakasý yok tamamen amacým eksi eþit nasýl olmasý



SELECT SUM(STOK) FROM TBLURUN

-- BU AÞAÐIDA YAZMIÞ OLDUGUMUZ SORGUDA ÇEÞÝT OLARAK 5 OLAN ÜRÜN SAYISINI TOPLAM STOÐA EÞÝTLEDÝK 5 SONUCU BÝZE 305 OLARAK DÖNDÜ

UPDATE TBLSTOK SET TOPLAMURUN=(SELECT SUM(STOK) FROM TBLURUN)







