update TBLOGRENCILER set OGRCINSIYET='Kýz' where OGRID=4 or OGRID=5



update TBLOGRENCILER set OGRKULUP='Kitaplýk' where OGRAD='baran'




insert into TBLNOTLAR (OGRENCI,ders,SINAV1,sýnav2) values (5,2,78,66)


update TBLNOTLAR set ORTLAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE OGRENCI =5

UPDATE TBLNOTLAR SET DURUM = 1 WHERE ORTLAMA>=50

UPDATE TBLNOTLAR SET DURUM = 0 WHERE ORTLAMA<50







