/*

Delete eylemi yani silme iþleminde hangi veriyi silmeye çalýþýyorsanýz silinen veriyi tespit etmek için deleted denen tablodan faydalanýrýz.

*/


CREATE TRIGGER AZALT
ON TBLURUN -- HANGÝ TABLODA ÇALIÞ TBLÜRÜN TABLOSUNDA
AFTER DELETE -- NE ZAMAN ÇALIÞ SÝLME ÝÞLEMÝNDEN SONRA
AS
DECLARE @STOKSAYI INT
SELECT @STOKSAYI=STOK FROM deleted -- SÝLÝNEN ÜRÜNÜN STOK DEÐERÝNÝ ALACAK

UPDATE TBLSTOK SET TOPLAMURUN = TOPLAMURUN-@STOKSAYI





-- TBL ÜRÜN TABLOSUNDAN  TOST MAKÝNASI ÝSÝMLÝ ÜRÜNÜ SÝLDÝK

DELETE FROM TBLURUN WHERE AD= 'TOST MAKÝNASI'


-- TBLÜRÜN TABLOSUNA ELLE VERÝ GÝRÝÞÝ YAPMIÞ OLDUK

INSERT into TBLURUN (AD,ALISFIYAT,SATISFIYAT,STOK,DURUM,KATEGORI) VALUES ('MIXER',80,90,25,1,3)