

-- ARADIÐIMIZ HERHANGÝ BÝR DATAYA NE KADAR SAYFA OKUYARAK ULAÞIYOR ONA BAKICAZ

SELECT * FROM TABLO1 WHERE ID=210387



-- BU ÜSTTEKÝ SORGUYA KAÇ SAYFA OKUYARAK ULAÞTI VE ÖNCESÝNDE OKUDUGUÐU SAYFALAR VARMI (SCAN ÝÞLEMÝ)

SET STATISTICS IO ON
SET STATISTICS TIME ON


SELECT * FROM TABLO1 WHERE ID=210387
