

-- ÞÝMDÝ BÝR TANE CLUSTERED ÝNDEX TANIMLICAZ

-- BÝR ÖNCEKÝ DERSDE YAZDIÐIMIZ SORGUDA 895 SAYFA OKUYARAK BULDU BURDA ÝSE CREATE CLUSTERED INDEX YAPARAK SADECE SAYFA OKUYARAK YAPMIÞ OLDU

CREATE CLUSTERED INDEX TABLOKAYITGETIR -- TABLOKAYITGETIR ÝSMÝNDE BÝR TANE CLUSTERED ÝNDEX OLUÞTURDUK
ON TABLO1(ID)  -- ON HANGÝ TABLO ÜZERÝNDE ÇALIÞACAK ve hangi sütuna göre çalýþacak ID sütuna göre çalýþacak

SET STATISTICS IO ON
SET STATISTICS TIME ON

SELECT * FROM TABLO1 WHERE ID=210387

SELECT * FROM TABLO1 WHERE ID=210087






